const haber8img = {
  introheader: require('../../src/assets/images/introheader.jpg'),
  authline: require('../../src/assets/images/authline.png'),
  haber8logo: require('../../src/assets/images/haber8logo.png'),
  bannerdata: require('../../src/assets/images/bannerdata.png'),
  dolarsline: require('../../src/assets/images/dolarsline.png'),
  newsdata1: require('../../src/assets/images/NewsData1.png'),
  newsdata2: require('../../src/assets/images/NewsData2.png'),
  newsdata3: require('../../src/assets/images/NewsData3.png'),
  newsdata4: require('../../src/assets/images/NewsData4.png'),
  yazarlarbg: require('../../src/assets/images/yazarlarbg.png'),
  yazar: require('../../src/assets/images/yazar.png'),
  sporline1: require('../../src/assets/images/sporlin1.png'),
  güncelhaberler1: require('../../src/assets/images/guncelhaberler1.png'),
  güncelhaberler2: require('../../src/assets/images/guncelhaberler2.png'),
  fotogaleriheader: require('../../src/assets/images/Fotogaleriheader.png'),
  fotogaleri1: require('../../src/assets/images/fotogaleri1.png'),
  fotogaleri2: require('../../src/assets/images/fotogaleri2.png'),
  namazvaktibg: require('../../src/assets/images/namazvaktibg.png'),
  videoheader: require('../../src/assets/images/vidoheader.png'),
  videothumbnail: require('../../src/assets/images/video.png'),
  yerelhaberler1: require('../../src/assets/images/yerelhaberler1.png'),
  yerelhaberler2: require('../../src/assets/images/yerelhaberler2.png'),
  yerelhaberler3: require('../../src/assets/images/yerelhaberler3.png'),
  havadurumu: require('../../src/assets/images/havadurumubg.png'),
  magazin: require('../../src/assets/images/magazin.png'),
  magazin1: require('../../src/assets/images/magazin1.png'),
  magazin2: require('../../src/assets/images/magazin2.png'),
  drawerheader: require('../../src/assets/images/DrawerHeaderBg.png'),
  nokta: require('../../src/assets/images/nokta.png'),
  yazarlarbg2: require('../../src/assets/images/Yazarlarbg2.png'),
  hdnvbg: require('../../src/assets/images/hdnvbg.png'),
  hddetail: require('../../src/assets/images/havadurumudetail.png'),
  ast1: require('../../src/assets/images/ast1.png'),
  ast2: require('../../src/assets/images/ast2.png'),
  ast3: require('../../src/assets/images/ast3.png'),
  ast4: require('../../src/assets/images/ast4.png'),
  ast5: require('../../src/assets/images/ast5.png'),
  notidot: require('../../src/assets/images/notidot.png'),
};

export default {
  haber8img,
};
